-
    name: Example group
    module:
        path: /Users/gennadiy/Yandex.Disk.localized/skree/src/modules/base/base.so
        config:
            lib:
                - /var/www/muh_kool_project
            package: MuhKoolProject::Skree
    events:
        -
            id: ExampleEvent
            ttl: 10
            batch_size: 10000
